name: Cypress Tests using Cypress Docker Image

on: [push]

jobs:
  cypress-run:
    #run on OS : ubuntu, docker container : cypress/browsers
    runs-on: ubuntu-latest
    container: cypress/browsers
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5 # use the explicit version number
        with:
          #record the tests to integrate with Cypress Cloud
          record: true
          parallel: true
          #Chrome browser for testing
          browser: chrome
        env:
          CYPRESS_RECORD_KEY : ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN }}
