name: Cypress Tests using Cypress Docker Image

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container: cypress/browsers
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5 # use the explicit version number
        strategy:
          fail-fast: false
          matrix:
            containers: [1,2]
        with:
          record: true
          parallel: true
          browser: chrome
        env:
          CYPRESS_RECORD_KEY : ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN }}
